# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: fun_with_files 0.0.18 ruby lib

Gem::Specification.new do |s|
  s.name = "fun_with_files".freeze
  s.version = "0.0.18".freeze

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Bryce Anderson".freeze]
  s.date = "2024-03-20"
  s.description = "  A more intuitive syntax for performing a variety of file actions. Examples:\n    \"/\".fwf_filepath.join('usr', 'bin', 'bash').touch\n    FunWith::Files::FilePath.home(\"Music\").glob(:ext => \"mp3\", :recurse => true)\n    home = FunWith::Files::FilePath.home\n    home.touch( \"Music\", \"CDs\", \"BubbleBoyTechnoRemixxxx2011\", \"01-jiggypalooza.mp3\" )\n    home.touch_dir( \"Music\", \"CDs\", \"ReggaeSmackdown2008\" ) do |dir|\n      dir.touch( \"liner_notes.txt\" )\n      dir.touch( \"cover.jpg\" )\n      dir.touch( \"01-tokin_by_the_sea.mp3\" )\n      dir.touch( \"02-tourists_be_crazy_mon.mp3\" )\n    end\n".freeze
  s.email = "keeputahweird@gmail.com".freeze
  s.extra_rdoc_files = [
    "CHANGELOG.markdown",
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    "./lib/fun_with/files/bootstrapper.rb",
    "./lib/fun_with/files/core_extensions/array.rb",
    "./lib/fun_with/files/core_extensions/false_class.rb",
    "./lib/fun_with/files/core_extensions/file.rb",
    "./lib/fun_with/files/core_extensions/hash.rb",
    "./lib/fun_with/files/core_extensions/nil_class.rb",
    "./lib/fun_with/files/core_extensions/object.rb",
    "./lib/fun_with/files/core_extensions/set.rb",
    "./lib/fun_with/files/core_extensions/string.rb",
    "./lib/fun_with/files/core_extensions/true_class.rb",
    "./lib/fun_with/files/digest_methods.rb",
    "./lib/fun_with/files/directory_builder.rb",
    "./lib/fun_with/files/downloader.rb",
    "./lib/fun_with/files/errors.rb",
    "./lib/fun_with/files/file_manipulation_methods.rb",
    "./lib/fun_with/files/file_orderer.rb",
    "./lib/fun_with/files/file_path.rb",
    "./lib/fun_with/files/file_path_class_methods.rb",
    "./lib/fun_with/files/file_permission_methods.rb",
    "./lib/fun_with/files/file_requirements.rb",
    "./lib/fun_with/files/gem_api.rb",
    "./lib/fun_with/files/pathname_extensions.rb",
    "./lib/fun_with/files/remote_path.rb",
    "./lib/fun_with/files/requirements/manager.rb",
    "./lib/fun_with/files/root_path.rb",
    "./lib/fun_with/files/stat_methods.rb",
    "./lib/fun_with/files/string_behavior.rb",
    "./lib/fun_with/files/string_extensions.rb",
    "./lib/fun_with/files/utils/byte_size.rb",
    "./lib/fun_with/files/utils/opts.rb",
    "./lib/fun_with/files/utils/succession.rb",
    "./lib/fun_with/files/utils/timestamp.rb",
    "./lib/fun_with/files/utils/timestamp_format.rb",
    "./lib/fun_with/files/watcher.rb",
    "./lib/fun_with/files/watchers/directory_watcher.rb",
    "./lib/fun_with/files/watchers/file_watcher.rb",
    "./lib/fun_with/files/watchers/missing_watcher.rb",
    "./lib/fun_with/files/watchers/node_watcher.rb",
    "./lib/fun_with/files/xdg_extensions.rb",
    "./lib/fun_with/testing/assertions/fun_with_files.rb",
    "./lib/fun_with/testing/test_case_extensions.rb",
    "./lib/fun_with_files.rb",
    "./test/data/empty.txt",
    "./test/data/grep1.txt",
    "./test/data/grep2.txt",
    "./test/data/gsub1.txt",
    "./test/data/gsub2.txt",
    "./test/helper.rb",
    "./test/loadable_dir/dir1/file1.rb",
    "./test/loadable_dir/dir2/file2.rb",
    "./test/loadable_dir/dir3/file3.rb",
    "./test/loadable_dir/dir4/file4.rb",
    "./test/loadable_dir/dir5/a.rb",
    "./test/loadable_dir/dir5/b.rb",
    "./test/loadable_dir/dir5/c.rb",
    "./test/loadable_dir/dir5/d.rb",
    "./test/test_copying.rb",
    "./test/test_core_extensions.rb",
    "./test/test_descent.rb",
    "./test/test_digest.rb",
    "./test/test_directory_builder.rb",
    "./test/test_extension_methods.rb",
    "./test/test_file_manipulation.rb",
    "./test/test_file_path.rb",
    "./test/test_file_requirements.rb",
    "./test/test_fun_with_files.rb",
    "./test/test_fwf_assertions.rb",
    "./test/test_globbing.rb",
    "./test/test_loading.rb",
    "./test/test_moving_files.rb",
    "./test/test_permission_methods.rb",
    "./test/test_root_path.rb",
    "./test/test_stat_methods.rb",
    "./test/test_symlinking.rb",
    "./test/test_timestamping.rb",
    "./test/test_touching.rb",
    "./test/test_utils_bytesize.rb",
    "./test/test_utils_succession.rb",
    "./test/test_watchers.rb",
    "Gemfile",
    "LICENSE.txt",
    "Rakefile",
    "VERSION"
  ]
  s.homepage = "http://github.com/darthschmoo/fun_with_files".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.5.6".freeze
  s.summary = "A mashup of several File, FileUtils, and Dir class functions, with a peppy, fun-loving syntax".freeze

  s.specification_version = 4

  s.add_runtime_dependency(%q<xdg>.freeze, ["~> 7".freeze])
  s.add_development_dependency(%q<debug>.freeze, [">= 0".freeze])
  s.add_development_dependency(%q<fun_with_testing>.freeze, ["~> 0.0".freeze, ">= 0.0.7".freeze])
end

